config/routes.rb
Rails.application.routes.draw do

  resources :questions do
    member do
      post "upvote"
      post "downvote"
    end
    resources :answers do
      member do
        post "upvote"
        post "downvote"
      end
    end
  end

  root 'questions#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  validates_presence_of :title, :content
  belongs_to :question
  has_many :votes, as: :votable, dependent: :destroy
end

app/models/github.rb
module Github

  class Client
    include HTTParty
    base_uri "https://api.github.com"

    def zen(access_token)
      headers = { "User-Agent" => "liorrm" }
      response = self.class.get('/zen', :query => { :access_token => access_token }, headers: headers)
      if response.headers['status'] == "403 Forbidden"
        Quote.rand_quote
      else
        p response
        Quote.create(quotes: response.body)
      end
    end

  end

end

app/models/question.rb
class Question < ActiveRecord::Base
  validates_presence_of :title, :content
  has_many :answers
  has_many :votes, as: :votable, dependent: :destroy

  def total_votes
    upvotes = self.votes.where(direction: "up").count
    downvotes = self.votes.where(direction: "down").count
    total_votes = upvotes - downvotes
    return total_votes
  end
end

app/models/quote.rb
  class Quote < ActiveRecord::Base
  def self.rand_quote
    limit = rand(Quote.count)
    rand_quote = Quote.offset(limit).first.quote
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :votable, polymorphic: true
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def upvote
    @question = Question.find(params[:question_id])
    @answer   = Answer.find(params[:id])
    @answer.votes.create(direction: :up)
    redirect_to :root
  end

  def downvote
    @question = Question.find(params[:question_id])
    @answer   = Answer.find(params[:id])
    @answer.votes.create(direction: :down)
    redirect_to :root
  end

  def create
    @question = Question.find(params[:question_id])
    answer    = @question.answers.create(answer_params)
    redirect_to question_path(@question)
    upvotes   = answer.votes.where(direction: :up).count
    downvotes = answer.votes.where(direction: :down).count
    @votes    = upvotes - downvotes
  end

  def answer_params
    params.require(:answer).permit(:title, :content)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def upvote
    @question = Question.find(params[:id])
    @question.votes.create(direction: :up)
    # @votes = @question.votes
    upvotes = @question.votes.where(direction: :up).count
    downvotes = @question.votes.where(direction: :down).count
    @votes = upvotes - downvotes
    @questions = Question.all
  end

  def downvote
    @questions = Question.all
    @question = Question.find(params[:id])
    @question.votes.create(direction: :down)
    # @votes = @question.votes
    upvotes = @question.votes.where(direction: :up).count ## numero
    downvotes = @question.votes.where(direction: :down).count ## numero
    @votes = upvotes - downvotes
  end

  def index ## get '/(questions)/' do
    @question = Question.new
    @questions = Question.all
    api = Github::Client.new
    @quote = api.zen(ENV['GITHUB_TOKEN']).quotes
    respond_to do |format|
      format.html
      format.json
    end
  end

  def show ## get '/questions/:id' do
    @question = Question.find(params[:id])
    upvotes = @question.votes.where(direction: :up).count
    downvotes = @question.votes.where(direction: :down).count
    @votes = upvotes - downvotes
    @question.answers
  end

  def new
    @question = Question.new
  end

  def create ## post '/questions' do
    @questions = Question.all
    @question = Question.new(question_params)
    @question.save
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
  @question = Question.find(params[:id])

  if @question.update(question_params)
    redirect_to @question
  else
    render 'edit'
  end
end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    redirect_to :root
  end

  private
    # Using a private method to encapsulate the permissible parameters
    # is just a good pattern since you'll be able to reuse the same
    # permit list between create and update. Also, you can specialize
    # this method with per-user checking of permissible attributes.
    def question_params
      params.require(:question).permit(:title, :content)
    end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DbcOverflow</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/questions/_form.html.erb
<%= form_for @question, url: questions_path, remote: true do |f| %>

  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@question.errors.count, "error") %> prohibited
        this question from being saved:
      </h2>
      <ul>
        <% @question.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/questions/_question.html.erb
<li><%= link_to question.title, question_path(question) %>
  <h4><%= question.total_votes %>
  </li>
  <%= button_to 'Upvote', upvote_question_path(question.id), remote: true %><%= button_to 'Downvote', downvote_question_path(question.id), remote: true %>

app/views/questions/_questions.html.erb
  <ul>
  <% @questions.each do |question| %>
    <li><%= link_to question.title, question_path(question) %> <h4><%= question.votes.where(direction: :up).count - question.votes.where(direction: :down).count %></li><%= button_to 'Upvote', upvote_question_path(question.id),remote: true %><%= button_to 'Downvote', downvote_question_path(question.id), remote: true %>
  <% end %>
  </ul>

app/views/questions/_vote.html.erb
Votes: <%= @votes %>

app/views/questions/create.js.erb
$('#questions').append("<%= j (render @question) %>");
$('#question-form').slideUp(350);

app/views/questions/downvote.js.erb
$('#questions').html('<%= j (render @questions) %>');

app/views/questions/edit.html.erb
<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<h1>Questions</h1>
<h2><%= @quote %></h2>

<div id="questions"><%= render "questions" %></div>


<%= link_to 'New Question', new_question_path, remote: true %>

<div id="question-form" style="display:none;">

app/views/questions/new.js.erb
$('#question-form').html("<%= j (render 'form') %>");
$('#question-form').slideDown(350);

app/views/questions/show.html.erb
<h1><%= @question.title %></h1><h2 id="votes"><%= render 'votes/vote' %></h2>
<h3><%= @question.content %><h3><%= button_to 'Upvote', upvote_question_path(@question.id), remote: true %>
<%= button_to 'Downvote', downvote_question_path(@question.id), remote: true %>
<br>
<%= link_to 'Edit Question', edit_question_path(@question) %>
 <%= link_to 'Destroy', question_path(@question),
              method: :delete,
              data: { confirm: 'Are you sure?' } %>

<h3>Answers:</h3>
<br>
<% @question.answers.each do |answer| %>
  <h3><%= answer.title  %></h3><h4><%= answer.votes.where(direction: :up).count - answer.votes.where(direction: :down).count  %></h4> <!-- I KNOW THIS IS TERRIBLE FORM!!!!!!!!!! -->
  <p><%= answer.content %></p>
  <%= button_to 'Upvote', upvote_question_answer_path(@question.id, answer.id) %>
  <%= button_to 'Downvote', downvote_question_answer_path(@question.id, answer.id) %>

<% end %>

<h3><%= link_to 'Back to Main', questions_path %></h3>

<%= form_for([@question, @question.answers.build]) do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/questions/upvote.js.erb
$('#questions').html('<%= j (render @questions) %>');

app/views/votes/_vote.html.erb
Votes: <%= @votes %>